#include "tabela_analise.h"
#include "acoes_semanticas.h"
#include "tabela_sdt_auxiliar.h"

#include <string.h>
#include <stddef.h>


extern const EntradaTabelaSDT tabela_sdt_entries[];
extern const size_t num_entradas_sdt; 

const ItemTabelaSDT* obter_itens_sdt(const char* chave, size_t* quantidade) {
    for (size_t i = 0; i < num_entradas_sdt; i++) {
        if (strcmp(tabela_sdt_entries[i].chave, chave) == 0) {
            *quantidade = tabela_sdt_entries[i].quantidade;
            return tabela_sdt_entries[i].itens;
        }
    }
    return NULL;
}

const EntradaTabelaAnalise tabela_analise[] = {
    {
        "PROGRAM",
        (MapeamentoTerminal[]) {
            {"DEF", "PROGRAM-DEF"},
            {"IDENT", "PROGRAM-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"OPEN_BRACE", "PROGRAM-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"INT", "PROGRAM-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"FLOAT", "PROGRAM-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"STRING", "PROGRAM-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"SEMICOLON", "PROGRAM-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"BREAK", "PROGRAM-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"PRINT", "PROGRAM-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"READ", "PROGRAM-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"RETURN", "PROGRAM-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"IF", "PROGRAM-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"FOR", "PROGRAM-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"$", "PROGRAM-$"}
        },
        14 // Número de mapeamentos para PROGRAM
    },
    {
        "PROGRAM'",
        (MapeamentoTerminal[]) {
            {"IDENT", "PROGRAM'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"OPEN_BRACE", "PROGRAM'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"INT", "PROGRAM'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"FLOAT", "PROGRAM'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"STRING", "PROGRAM'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"SEMICOLON", "PROGRAM'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"BREAK", "PROGRAM'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"PRINT", "PROGRAM'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"READ", "PROGRAM'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"RETURN", "PROGRAM'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"IF", "PROGRAM'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"FOR", "PROGRAM'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"$", "PROGRAM'-$"}
        },
        13 // Número de mapeamentos
    },
    {
        "FUNCLIST",
        (MapeamentoTerminal[]) {
            {"DEF", "FUNCLIST-DEF"},
        },
        1
    },
    {
        "FUNCLIST'",
        (MapeamentoTerminal[]) {
            {"DEF", "FUNCLIST'-DEF"},
            {"IDENT", "FUNCLIST'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR-$"},
            {"OPEN_BRACE", "FUNCLIST'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR-$"},
            {"INT", "FUNCLIST'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR-$"},
            {"FLOAT", "FUNCLIST'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR-$"},
            {"STRING", "FUNCLIST'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR-$"},
            {"SEMICOLON", "FUNCLIST'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR-$"},
            {"BREAK", "FUNCLIST'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR-$"},
            {"PRINT", "FUNCLIST'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR-$"},
            {"READ", "FUNCLIST'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR-$"},
            {"RETURN", "FUNCLIST'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR-$"},
            {"IF", "FUNCLIST'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR-$"},
            {"FOR", "FUNCLIST'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR-$"},
            {"$", "FUNCLIST'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR-$"}
        },
        14
    },
    {
        "FUNCDEF",
        (MapeamentoTerminal[]) {
            {"DEF", "FUNCDEF-DEF"},
        },
        1
    },
    {
        "PARAMLIST",
        (MapeamentoTerminal[]) {
            {"CLOSE_PARENTHESIS", "PARAMLIST-CLOSE_PARENTHESIS"},
            {"INT", "PARAMLIST-INT"},
            {"FLOAT", "PARAMLIST-FLOAT"},
            {"STRING", "PARAMLIST-STRING"},
        },
        4
    },
    {
        "PARAMLIST'",
        (MapeamentoTerminal[]) {
            {"CLOSE_PARENTHESIS", "PARAMLIST'-CLOSE_PARENTHESIS"},
            {"COMMA", "PARAMLIST'-COMMA"},
        },
        2
    },
    {
        "STATEMENT",
        (MapeamentoTerminal[]) {
            {"IDENT", "STATEMENT-IDENT"},
            {"OPEN_BRACE", "STATEMENT-OPEN_BRACE"},
            {"INT", "STATEMENT-INT-FLOAT-STRING"},
            {"FLOAT", "STATEMENT-INT-FLOAT-STRING"},
            {"STRING", "STATEMENT-INT-FLOAT-STRING"},
            {"SEMICOLON", "STATEMENT-SEMICOLON"},
            {"BREAK", "STATEMENT-BREAK"},
            {"PRINT", "STATEMENT-PRINT"},
            {"READ", "STATEMENT-READ"},
            {"RETURN", "STATEMENT-RETURN"},
            {"IF", "STATEMENT-IF"},
            {"FOR", "STATEMENT-FOR"},
        },
        12
    },
    {
        "INDEX",
        (MapeamentoTerminal[]) {
            {"SEMICOLON", "INDEX-SEMICOLON"},
            {"OPEN_BRACKET", "INDEX-OPEN_BRACKET"},
        },
        2
    },
    {
        "VARDECL",
        (MapeamentoTerminal[]) {
            {"INT", "VARDECL-INT"},
            {"FLOAT", "VARDECL-FLOAT"},
            {"STRING", "VARDECL-STRING"},
        },
        3
    },
    {
        "ATRIBSTAT",
        (MapeamentoTerminal[]) {
            {"IDENT", "ATRIBSTAT-IDENT"},
        },
        1
    },
    {
        "ATRIBSTAT'",
        (MapeamentoTerminal[]) {
            {"IDENT", "ATRIBSTAT'-IDENT-OPEN_PARENTHESIS-NI-PLUS-MINUS-NPF-STRC-NULL"},
            {"OPEN_PARENTHESIS", "ATRIBSTAT'-IDENT-OPEN_PARENTHESIS-NI-PLUS-MINUS-NPF-STRC-NULL"},
            {"NI", "ATRIBSTAT'-IDENT-OPEN_PARENTHESIS-NI-PLUS-MINUS-NPF-STRC-NULL"},
            {"PLUS", "ATRIBSTAT'-IDENT-OPEN_PARENTHESIS-NI-PLUS-MINUS-NPF-STRC-NULL"},
            {"MINUS", "ATRIBSTAT'-IDENT-OPEN_PARENTHESIS-NI-PLUS-MINUS-NPF-STRC-NULL"},
            {"NPF", "ATRIBSTAT'-IDENT-OPEN_PARENTHESIS-NI-PLUS-MINUS-NPF-STRC-NULL"},
            {"STRC", "ATRIBSTAT'-IDENT-OPEN_PARENTHESIS-NI-PLUS-MINUS-NPF-STRC-NULL"},
            {"NULL", "ATRIBSTAT'-IDENT-OPEN_PARENTHESIS-NI-PLUS-MINUS-NPF-STRC-NULL"},
            {"CALL", "ATRIBSTAT'-CALL"},
            {"NEW", "ATRIBSTAT'-NEW"},
        },
        10
    },
    {
        "FUNCCALL",
        (MapeamentoTerminal[]) {
            {"CALL", "FUNCCALL-CALL"},
        },
        1
    },
    {
        "PARAMLISTCALL",
        (MapeamentoTerminal[]) {
            {"IDENT", "PARAMLISTCALL-IDENT"},
            {"CLOSE_PARENTHESIS", "PARAMLISTCALL-CLOSE_PARENTHESIS"},
        },
        2
    },
    {
        "PARAMLISTCALL'",
        (MapeamentoTerminal[]) {
            {"CLOSE_PARENTHESIS", "PARAMLISTCALL'-CLOSE_PARENTHESIS"},
            {"COMMA", "PARAMLISTCALL'-COMMA"},
        },
        2
    },
    {
        "PRINTSTAT",
        (MapeamentoTerminal[]) {
            {"PRINT", "PRINTSTAT-PRINT"},
        },
        1
    },
    {
        "READSTAT",
        (MapeamentoTerminal[]) {
            {"READ", "READSTAT-READ"},
        },
        1
    },
    {
        "RETURNSTAT",
        (MapeamentoTerminal[]) {
            {"RETURN", "RETURNSTAT-RETURN"},
        },
        1
    },
    {
        "RETURNSTAT'",
        (MapeamentoTerminal[]) {
            {"IDENT", "RETURNSTAT'-IDENT"},
            {"SEMICOLON", "RETURNSTAT'-SEMICOLON"},
        },
        2
    },
    {
        "IFSTAT",
        (MapeamentoTerminal[]) {
            {"IF", "IFSTAT-IF"},
        },
        1
    },
    {
        "IFSTAT'",
        (MapeamentoTerminal[]) {
            {"IDENT", "IFSTAT'-IDENT-OPEN_BRACE-CLOSE_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR-$"},
            {"OPEN_BRACE", "IFSTAT'-IDENT-OPEN_BRACE-CLOSE_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR-$"},
            {"CLOSE_BRACE", "IFSTAT'-IDENT-OPEN_BRACE-CLOSE_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR-$"},
            {"INT", "IFSTAT'-IDENT-OPEN_BRACE-CLOSE_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR-$"},
            {"FLOAT", "IFSTAT'-IDENT-OPEN_BRACE-CLOSE_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR-$"},
            {"STRING", "IFSTAT'-IDENT-OPEN_BRACE-CLOSE_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR-$"},
            {"SEMICOLON", "IFSTAT'-IDENT-OPEN_BRACE-CLOSE_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR-$"},
            {"BREAK", "IFSTAT'-IDENT-OPEN_BRACE-CLOSE_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR-$"},
            {"PRINT", "IFSTAT'-IDENT-OPEN_BRACE-CLOSE_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR-$"},
            {"READ", "IFSTAT'-IDENT-OPEN_BRACE-CLOSE_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR-$"},
            {"RETURN", "IFSTAT'-IDENT-OPEN_BRACE-CLOSE_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR-$"},
            {"IF", "IFSTAT'-IDENT-OPEN_BRACE-CLOSE_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR-$"},
            {"FOR", "IFSTAT'-IDENT-OPEN_BRACE-CLOSE_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR-$"},
            {"$", "IFSTAT'-IDENT-OPEN_BRACE-CLOSE_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR-$"},
            {"ELSE", "IFSTAT'-ELSE"},
        },
        15
    },
    {
        "FORSTAT",
        (MapeamentoTerminal[]) {
            {"FOR", "FORSTAT-FOR"},
        },
        1
    },
    {
        "STATELIST",
        (MapeamentoTerminal[]) {
            {"IDENT", "STATELIST-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"OPEN_BRACE", "STATELIST-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"INT", "STATELIST-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"FLOAT", "STATELIST-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"STRING", "STATELIST-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"SEMICOLON", "STATELIST-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"BREAK", "STATELIST-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"PRINT", "STATELIST-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"READ", "STATELIST-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"RETURN", "STATELIST-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"IF", "STATELIST-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"FOR", "STATELIST-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
        },
        12
    },
    {
        "STATELIST'",
        (MapeamentoTerminal[]) {
            {"IDENT", "STATELIST'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"OPEN_BRACE", "STATELIST'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"INT", "STATELIST'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"FLOAT", "STATELIST'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"STRING", "STATELIST'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"SEMICOLON", "STATELIST'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"BREAK", "STATELIST'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"PRINT", "STATELIST'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"READ", "STATELIST'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"RETURN", "STATELIST'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"IF", "STATELIST'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"FOR", "STATELIST'-IDENT-OPEN_BRACE-INT-FLOAT-STRING-SEMICOLON-BREAK-PRINT-READ-RETURN-IF-FOR"},
            {"CLOSE_BRACE", "STATELIST'-CLOSE_BRACE"},
        },
        13
    },
    {
        "ALLOCAUX",
        (MapeamentoTerminal[]) {
            {"CLOSE_PARENTHESIS", "ALLOCAUX-CLOSE_PARENTHESIS-SEMICOLON-CLOSE_BRACKET-ASSIGN-RELOP-PLUS-MINUS-MULTIPLICATION-DIVISION-MODULUS"},
            {"SEMICOLON", "ALLOCAUX-CLOSE_PARENTHESIS-SEMICOLON-CLOSE_BRACKET-ASSIGN-RELOP-PLUS-MINUS-MULTIPLICATION-DIVISION-MODULUS"},
            {"CLOSE_BRACKET", "ALLOCAUX-CLOSE_PARENTHESIS-SEMICOLON-CLOSE_BRACKET-ASSIGN-RELOP-PLUS-MINUS-MULTIPLICATION-DIVISION-MODULUS"},
            {"ASSIGN", "ALLOCAUX-CLOSE_PARENTHESIS-SEMICOLON-CLOSE_BRACKET-ASSIGN-RELOP-PLUS-MINUS-MULTIPLICATION-DIVISION-MODULUS"},
            {"RELOP", "ALLOCAUX-CLOSE_PARENTHESIS-SEMICOLON-CLOSE_BRACKET-ASSIGN-RELOP-PLUS-MINUS-MULTIPLICATION-DIVISION-MODULUS"},
            {"PLUS", "ALLOCAUX-CLOSE_PARENTHESIS-SEMICOLON-CLOSE_BRACKET-ASSIGN-RELOP-PLUS-MINUS-MULTIPLICATION-DIVISION-MODULUS"},
            {"MINUS", "ALLOCAUX-CLOSE_PARENTHESIS-SEMICOLON-CLOSE_BRACKET-ASSIGN-RELOP-PLUS-MINUS-MULTIPLICATION-DIVISION-MODULUS"},
            {"MULTIPLICATION", "ALLOCAUX-CLOSE_PARENTHESIS-SEMICOLON-CLOSE_BRACKET-ASSIGN-RELOP-PLUS-MINUS-MULTIPLICATION-DIVISION-MODULUS"},
            {"DIVISION", "ALLOCAUX-CLOSE_PARENTHESIS-SEMICOLON-CLOSE_BRACKET-ASSIGN-RELOP-PLUS-MINUS-MULTIPLICATION-DIVISION-MODULUS"},
            {"MODULUS", "ALLOCAUX-CLOSE_PARENTHESIS-SEMICOLON-CLOSE_BRACKET-ASSIGN-RELOP-PLUS-MINUS-MULTIPLICATION-DIVISION-MODULUS"},
            {"OPEN_BRACKET", "ALLOCAUX-OPEN_BRACKET"},
        },
        11
    },
    {
        "ALLOCEXPRESSION",
        (MapeamentoTerminal[]) {
            {"NEW", "ALLOCEXPRESSION-NEW"},
        },
        1
    },
    {
        "ALLOCEXPRESSION'",
        (MapeamentoTerminal[]) {
            {"INT", "ALLOCEXPRESSION'-INT"},
            {"FLOAT", "ALLOCEXPRESSION'-FLOAT"},
            {"STRING", "ALLOCEXPRESSION'-STRING"},
        },
        3
    },
    {
        "EXPRESSION",
        (MapeamentoTerminal[]) {
            {"IDENT", "EXPRESSION-IDENT-OPEN_PARENTHESIS-NI-PLUS-MINUS-NPF-STRC-NULL"},
            {"OPEN_PARENTHESIS", "EXPRESSION-IDENT-OPEN_PARENTHESIS-NI-PLUS-MINUS-NPF-STRC-NULL"},
            {"NI", "EXPRESSION-IDENT-OPEN_PARENTHESIS-NI-PLUS-MINUS-NPF-STRC-NULL"},
            {"PLUS", "EXPRESSION-IDENT-OPEN_PARENTHESIS-NI-PLUS-MINUS-NPF-STRC-NULL"},
            {"MINUS", "EXPRESSION-IDENT-OPEN_PARENTHESIS-NI-PLUS-MINUS-NPF-STRC-NULL"},
            {"NPF", "EXPRESSION-IDENT-OPEN_PARENTHESIS-NI-PLUS-MINUS-NPF-STRC-NULL"},
            {"STRC", "EXPRESSION-IDENT-OPEN_PARENTHESIS-NI-PLUS-MINUS-NPF-STRC-NULL"},
            {"NULL", "EXPRESSION-IDENT-OPEN_PARENTHESIS-NI-PLUS-MINUS-NPF-STRC-NULL"},
        },
        8
    },
    {
        "EXPRESSION'",
        (MapeamentoTerminal[]) {
            {"CLOSE_PARENTHESIS", "EXPRESSION'-CLOSE_PARENTHESIS-SEMICOLON"},
            {"SEMICOLON", "EXPRESSION'-CLOSE_PARENTHESIS-SEMICOLON"},
            {"RELOP", "EXPRESSION'-RELOP"},
        },
        3
    },
    {
        "NUMEXPRESSIONAUX",
        (MapeamentoTerminal[]) {
            {"CLOSE_PARENTHESIS", "NUMEXPRESSIONAUX-CLOSE_PARENTHESIS-SEMICOLON-CLOSE_BRACKET-RELOP"},
            {"SEMICOLON", "NUMEXPRESSIONAUX-CLOSE_PARENTHESIS-SEMICOLON-CLOSE_BRACKET-RELOP"},
            {"CLOSE_BRACKET", "NUMEXPRESSIONAUX-CLOSE_PARENTHESIS-SEMICOLON-CLOSE_BRACKET-RELOP"},
            {"RELOP", "NUMEXPRESSIONAUX-CLOSE_PARENTHESIS-SEMICOLON-CLOSE_BRACKET-RELOP"},
            {"PLUS", "NUMEXPRESSIONAUX-PLUS"},
            {"MINUS", "NUMEXPRESSIONAUX-MINUS"},
        },
        6
    },
    {
        "NUMEXPRESSION",
        (MapeamentoTerminal[]) {
            {"IDENT", "NUMEXPRESSION-IDENT-OPEN_PARENTHESIS-NI-PLUS-MINUS-NPF-STRC-NULL"},
            {"OPEN_PARENTHESIS", "NUMEXPRESSION-IDENT-OPEN_PARENTHESIS-NI-PLUS-MINUS-NPF-STRC-NULL"},
            {"NI", "NUMEXPRESSION-IDENT-OPEN_PARENTHESIS-NI-PLUS-MINUS-NPF-STRC-NULL"},
            {"PLUS", "NUMEXPRESSION-IDENT-OPEN_PARENTHESIS-NI-PLUS-MINUS-NPF-STRC-NULL"},
            {"MINUS", "NUMEXPRESSION-IDENT-OPEN_PARENTHESIS-NI-PLUS-MINUS-NPF-STRC-NULL"},
            {"NPF", "NUMEXPRESSION-IDENT-OPEN_PARENTHESIS-NI-PLUS-MINUS-NPF-STRC-NULL"},
            {"STRC", "NUMEXPRESSION-IDENT-OPEN_PARENTHESIS-NI-PLUS-MINUS-NPF-STRC-NULL"},
            {"NULL", "NUMEXPRESSION-IDENT-OPEN_PARENTHESIS-NI-PLUS-MINUS-NPF-STRC-NULL"},
        },
        8
    },
    {
        "TERM",
        (MapeamentoTerminal[]) {
            {"IDENT", "TERM-IDENT-OPEN_PARENTHESIS-NI-PLUS-MINUS-NPF-STRC-NULL"},
            {"OPEN_PARENTHESIS", "TERM-IDENT-OPEN_PARENTHESIS-NI-PLUS-MINUS-NPF-STRC-NULL"},
            {"NI", "TERM-IDENT-OPEN_PARENTHESIS-NI-PLUS-MINUS-NPF-STRC-NULL"},
            {"PLUS", "TERM-IDENT-OPEN_PARENTHESIS-NI-PLUS-MINUS-NPF-STRC-NULL"},
            {"MINUS", "TERM-IDENT-OPEN_PARENTHESIS-NI-PLUS-MINUS-NPF-STRC-NULL"},
            {"NPF", "TERM-IDENT-OPEN_PARENTHESIS-NI-PLUS-MINUS-NPF-STRC-NULL"},
            {"STRC", "TERM-IDENT-OPEN_PARENTHESIS-NI-PLUS-MINUS-NPF-STRC-NULL"},
            {"NULL", "TERM-IDENT-OPEN_PARENTHESIS-NI-PLUS-MINUS-NPF-STRC-NULL"},
        },
        8
    },
    {
        "UNARYEXPRAUX",
        (MapeamentoTerminal[]) {
            {"CLOSE_PARENTHESIS", "UNARYEXPRAUX-CLOSE_PARENTHESIS-SEMICOLON-CLOSE_BRACKET-RELOP-PLUS-MINUS"},
            {"SEMICOLON", "UNARYEXPRAUX-CLOSE_PARENTHESIS-SEMICOLON-CLOSE_BRACKET-RELOP-PLUS-MINUS"},
            {"CLOSE_BRACKET", "UNARYEXPRAUX-CLOSE_PARENTHESIS-SEMICOLON-CLOSE_BRACKET-RELOP-PLUS-MINUS"},
            {"RELOP", "UNARYEXPRAUX-CLOSE_PARENTHESIS-SEMICOLON-CLOSE_BRACKET-RELOP-PLUS-MINUS"},
            {"PLUS", "UNARYEXPRAUX-CLOSE_PARENTHESIS-SEMICOLON-CLOSE_BRACKET-RELOP-PLUS-MINUS"},
            {"MINUS", "UNARYEXPRAUX-CLOSE_PARENTHESIS-SEMICOLON-CLOSE_BRACKET-RELOP-PLUS-MINUS"},
            {"MULTIPLICATION", "UNARYEXPRAUX-MULTIPLICATION"},
            {"DIVISION", "UNARYEXPRAUX-DIVISION"},
            {"MODULUS", "UNARYEXPRAUX-MODULUS"},
        },
        9
    },
    {
        "UNARYEXPR",
        (MapeamentoTerminal[]) {
            {"IDENT", "UNARYEXPR-IDENT-OPEN_PARENTHESIS-NI-NPF-STRC-NULL"},
            {"OPEN_PARENTHESIS", "UNARYEXPR-IDENT-OPEN_PARENTHESIS-NI-NPF-STRC-NULL"},
            {"NI", "UNARYEXPR-IDENT-OPEN_PARENTHESIS-NI-NPF-STRC-NULL"},
            {"NPF", "UNARYEXPR-IDENT-OPEN_PARENTHESIS-NI-NPF-STRC-NULL"},
            {"STRC", "UNARYEXPR-IDENT-OPEN_PARENTHESIS-NI-NPF-STRC-NULL"},
            {"NULL", "UNARYEXPR-IDENT-OPEN_PARENTHESIS-NI-NPF-STRC-NULL"},
            {"PLUS", "UNARYEXPR-PLUS"},
            {"MINUS", "UNARYEXPR-MINUS"},
        },
        8
    },
    {
        "FACTOR",
        (MapeamentoTerminal[]) {
            {"IDENT", "FACTOR-IDENT"},
            {"OPEN_PARENTHESIS", "FACTOR-OPEN_PARENTHESIS"},
            {"NI", "FACTOR-NI"},
            {"NPF", "FACTOR-NPF"},
            {"STRC", "FACTOR-STRC"},
            {"NULL", "FACTOR-NULL"},
        },
        6
    },
    {
        "LVALUE",
        (MapeamentoTerminal[]) {
            {"IDENT", "LVALUE-IDENT"},
        },
        1
    }
};

const size_t num_entradas_tabela = sizeof(tabela_analise) / sizeof(EntradaTabelaAnalise);

