#include "tabela_analise.h"

/*
 * IMPORTANTE — ORDEM LEXICOGRÁFICA OBRIGATÓRIA
 *
 * Esta tabela **precisa** permanecer estritamente ordenada
 * em ordem lexicográfica. Qualquer entrada fora de ordem
 * faz com que as buscas binárias (bsearch) falhem e o
 * compilador passe a produzir resultados incorretos.
 *
 * ➜ Ao adicionar ou remover regras:
 *     1. Insira‑as já na posição correta.
 *     2. Verifique a ordem com um script ou diff.
 *
 * Não ignore este aviso: desordenar a lista quebra o
 * compilador.
 */

// TABELA DE ANÁLISE PREDITIVA (LL)
const EntradaTabelaAnalise tabela_analise[] = {
    {"ALLOCAUX", "ASSIGN", "ALLOCAUX->EPSILON"},
    {"ALLOCAUX", "CLOSE_BRACKET", "ALLOCAUX->EPSILON"},
    {"ALLOCAUX", "CLOSE_PARENTHESIS", "ALLOCAUX->EPSILON"},
    {"ALLOCAUX", "DIVISION", "ALLOCAUX->EPSILON"},
    {"ALLOCAUX", "MINUS", "ALLOCAUX->EPSILON"},
    {"ALLOCAUX", "MODULUS", "ALLOCAUX->EPSILON"},
    {"ALLOCAUX", "MULTIPLICATION", "ALLOCAUX->EPSILON"},
    {"ALLOCAUX", "OPEN_BRACKET", "ALLOCAUX->BRACKET"},
    {"ALLOCAUX", "PLUS", "ALLOCAUX->EPSILON"},
    {"ALLOCAUX", "RELOP", "ALLOCAUX->EPSILON"},
    {"ALLOCAUX", "SEMICOLON", "ALLOCAUX->EPSILON"},
    {"ALLOCEXPRESSION", "NEW", "ALLOCEXPR->NEW"},
    {"ALLOCEXPRESSION'", "FLOAT", "ALLOCEXPR'->TYPE"},
    {"ALLOCEXPRESSION'", "INT", "ALLOCEXPR'->TYPE"},
    {"ALLOCEXPRESSION'", "STRING", "ALLOCEXPR'->TYPE"},
    {"ATRIBSTAT", "IDENT", "ATRIBSTAT->IDENT"},
    {"ATRIBSTAT'", "CALL", "ATRIB'->FUNCCALL"},
    {"ATRIBSTAT'", "IDENT", "ATRIB'->EXPRESSION"},
    {"ATRIBSTAT'", "MINUS", "ATRIB'->EXPRESSION"},
    {"ATRIBSTAT'", "NEW", "ATRIB'->ALLOCEXPR"},
    {"ATRIBSTAT'", "NI", "ATRIB'->EXPRESSION"},
    {"ATRIBSTAT'", "NPF", "ATRIB'->EXPRESSION"},
    {"ATRIBSTAT'", "NULL", "ATRIB'->EXPRESSION"},
    {"ATRIBSTAT'", "OPEN_PARENTHESIS", "ATRIB'->EXPRESSION"},
    {"ATRIBSTAT'", "PLUS", "ATRIB'->EXPRESSION"},
    {"ATRIBSTAT'", "STRC", "ATRIB'->EXPRESSION"},
    {"CLOSE_BRACE", "$", "CLOSE_BRACE->EPSILON"},
    {"EXPRESSION", "IDENT", "EXPR->NUMEXPR"},
    {"EXPRESSION", "MINUS", "EXPR->NUMEXPR"},
    {"EXPRESSION", "NI", "EXPR->NUMEXPR"},
    {"EXPRESSION", "NPF", "EXPR->NUMEXPR"},
    {"EXPRESSION", "NULL", "EXPR->NUMEXPR"},
    {"EXPRESSION", "OPEN_PARENTHESIS", "EXPR->NUMEXPR"},
    {"EXPRESSION", "PLUS", "EXPR->NUMEXPR"},
    {"EXPRESSION", "STRC", "EXPR->NUMEXPR"},
    {"EXPRESSION'", "CLOSE_PARENTHESIS", "EXPR'->EPSILON"},
    {"EXPRESSION'", "RELOP", "EXPR'->RELOP"},
    {"EXPRESSION'", "SEMICOLON", "EXPR'->EPSILON"},
    {"FACTOR", "IDENT", "FACTOR->LVALUE"},
    {"FACTOR", "NI", "FACTOR->CONST_NI"},
    {"FACTOR", "NPF", "FACTOR->CONST_NPF"},
    {"FACTOR", "NULL", "FACTOR->CONST_NULL"},
    {"FACTOR", "OPEN_PARENTHESIS", "FACTOR->PARENTHESIS"},
    {"FACTOR", "STRC", "FACTOR->CONST_STRC"},
    {"FORSTAT", "FOR", "FORSTAT->FOR"},
    {"FUNCCALL", "CALL", "FUNCCALL->CALL"},
    {"FUNCDEF", "DEF", "FUNCDEF->DEF"},
    {"FUNCLIST", "DEF", "FUNCLIST->DEF"},
    {"FUNCLIST'", "$", "FUNCLIST'->EPSILON"},
    {"FUNCLIST'", "BREAK", "FUNCLIST'->EPSILON"},
    {"FUNCLIST'", "DEF", "FUNCLIST'->DEF"},
    {"FUNCLIST'", "FLOAT", "FUNCLIST'->EPSILON"},
    {"FUNCLIST'", "FOR", "FUNCLIST'->EPSILON"},
    {"FUNCLIST'", "IDENT", "FUNCLIST'->EPSILON"},
    {"FUNCLIST'", "IF", "FUNCLIST'->EPSILON"},
    {"FUNCLIST'", "INT", "FUNCLIST'->EPSILON"},
    {"FUNCLIST'", "ONECHAR", "FUNCLIST'->EPSILON"},
    {"FUNCLIST'", "PRINT", "FUNCLIST'->EPSILON"},
    {"FUNCLIST'", "READ", "FUNCLIST'->EPSILON"},
    {"FUNCLIST'", "RETURN", "FUNCLIST'->EPSILON"},
    {"FUNCLIST'", "SEMICOLON", "FUNCLIST'->EPSILON"},
    {"FUNCLIST'", "STRING", "FUNCLIST'->EPSILON"},
    {"IFSTAT", "IF", "IFSTAT->IF"},
    {"IFSTAT'", "$", "IFSTAT'->EPSILON"},
    {"IFSTAT'", "BREAK", "IFSTAT'->EPSILON"},
    {"IFSTAT'", "CLOSE_BRACE", "IFSTAT'->EPSILON"},
    {"IFSTAT'", "ELSE", "IFSTAT'->ELSE"},
    {"IFSTAT'", "FLOAT", "IFSTAT'->EPSILON"},
    {"IFSTAT'", "FOR", "IFSTAT'->EPSILON"},
    {"IFSTAT'", "IDENT", "IFSTAT'->EPSILON"},
    {"IFSTAT'", "IF", "IFSTAT'->EPSILON"},
    {"IFSTAT'", "INT", "IFSTAT'->EPSILON"},
    {"IFSTAT'", "ONECHAR", "IFSTAT'->EPSILON"},
    {"IFSTAT'", "PRINT", "IFSTAT'->EPSILON"},
    {"IFSTAT'", "READ", "IFSTAT'->EPSILON"},
    {"IFSTAT'", "RETURN", "IFSTAT'->EPSILON"},
    {"IFSTAT'", "SEMICOLON", "IFSTAT'->EPSILON"},
    {"IFSTAT'", "STRING", "IFSTAT'->EPSILON"},
    {"INDEX", "CLOSE_PARENTHESIS", "INDEX->EPSILON"},
    {"INDEX", "COMMA", "INDEX->EPSILON"},
    {"INDEX", "OPEN_BRACKET", "INDEX->BRACKET"},
    {"INDEX", "SEMICOLON", "INDEX->EPSILON"},
    {"LVALUE", "IDENT", "LVALUE->IDENT"},
    {"NUMEXPRESSION", "IDENT", "NUMEXPR->TERM"},
    {"NUMEXPRESSION", "MINUS", "NUMEXPR->TERM"},
    {"NUMEXPRESSION", "NI", "NUMEXPR->TERM"},
    {"NUMEXPRESSION", "NPF", "NUMEXPR->TERM"},
    {"NUMEXPRESSION", "NULL", "NUMEXPR->TERM"},
    {"NUMEXPRESSION", "OPEN_PARENTHESIS", "NUMEXPR->TERM"},
    {"NUMEXPRESSION", "PLUS", "NUMEXPR->TERM"},
    {"NUMEXPRESSION", "STRC", "NUMEXPR->TERM"},
    {"NUMEXPRESSIONAUX", "CLOSE_BRACKET", "NUMEXPR_AUX->EPSILON"},
    {"NUMEXPRESSIONAUX", "CLOSE_PARENTHESIS", "NUMEXPR_AUX->EPSILON"},
    {"NUMEXPRESSIONAUX", "MINUS", "NUMEXPR_AUX->MINUS"},
    {"NUMEXPRESSIONAUX", "PLUS", "NUMEXPR_AUX->PLUS"},
    {"NUMEXPRESSIONAUX", "RELOP", "NUMEXPR_AUX->EPSILON"},
    {"NUMEXPRESSIONAUX", "SEMICOLON", "NUMEXPR_AUX->EPSILON"},
    {"PARAMLIST", "CLOSE_PARENTHESIS", "PARAMLIST->EPSILON"},
    {"PARAMLIST", "FLOAT", "PARAMLIST->TYPE"},
    {"PARAMLIST", "INT", "PARAMLIST->TYPE"},
    {"PARAMLIST", "STRING", "PARAMLIST->TYPE"},
    {"PARAMLIST'", "CLOSE_PARENTHESIS", "PARAMLIST'->EPSILON"},
    {"PARAMLIST'", "COMMA", "PARAMLIST'->COMMA"},
    {"PARAMLISTCALL", "CLOSE_PARENTHESIS", "PARAMLISTCALL->EPSILON"},
    {"PARAMLISTCALL", "IDENT", "PARAMLISTCALL->IDENT"},
    {"PARAMLISTCALL'", "CLOSE_PARENTHESIS", "PARAMLISTCALL'->EPSILON"},
    {"PARAMLISTCALL'", "COMMA", "PARAMLISTCALL'->COMMA"},
    {"PRINTSTAT", "PRINT", "PRINTSTAT->PRINT"},
    {"PROGRAM", "$", "PROG->EPSILON"},
    {"PROGRAM", "BREAK", "PROG->STATEMENT"},
    {"PROGRAM", "DEF", "PROG->FUNCLIST"},
    {"PROGRAM", "FLOAT", "PROG->STATEMENT"},
    {"PROGRAM", "FOR", "PROG->STATEMENT"},
    {"PROGRAM", "IDENT", "PROG->STATEMENT"},
    {"PROGRAM", "IF", "PROG->STATEMENT"},
    {"PROGRAM", "INT", "PROG->STATEMENT"},
    {"PROGRAM", "ONECHAR", "PROG->STATEMENT"},
    {"PROGRAM", "PRINT", "PROG->STATEMENT"},
    {"PROGRAM", "READ", "PROG->STATEMENT"},
    {"PROGRAM", "RETURN", "PROG->STATEMENT"},
    {"PROGRAM", "SEMICOLON", "PROG->STATEMENT"},
    {"PROGRAM", "STRING", "PROG->STATEMENT"},
    {"PROGRAM'", "$", "PROG'->EPSILON"},
    {"PROGRAM'", "BREAK", "PROG'->STATEMENT"},
    {"PROGRAM'", "DEF", "PROG'->FUNCLIST"},
    {"PROGRAM'", "FLOAT", "PROG'->STATEMENT"},
    {"PROGRAM'", "FOR", "PROG'->STATEMENT"},
    {"PROGRAM'", "IDENT", "PROG'->STATEMENT"},
    {"PROGRAM'", "IF", "PROG'->STATEMENT"},
    {"PROGRAM'", "INT", "PROG'->STATEMENT"},
    {"PROGRAM'", "ONECHAR", "PROG'->STATEMENT"},
    {"PROGRAM'", "PRINT", "PROG'->STATEMENT"},
    {"PROGRAM'", "READ", "PROG'->STATEMENT"},
    {"PROGRAM'", "RETURN", "PROG'->STATEMENT"},
    {"PROGRAM'", "SEMICOLON", "PROG'->STATEMENT"},
    {"PROGRAM'", "STRING", "PROG'->STATEMENT"},
    {"READSTAT", "READ", "READSTAT->READ"},
    {"READSTAT", "READ", "READSTAT->READ"},
    {"RETURNSTAT", "RETURN", "RETURNSTAT->RETURN"},
    {"RETURNSTAT'", "IDENT", "RETURN'->EXPRESSION"},
    {"RETURNSTAT'", "MINUS", "RETURN'->EXPRESSION"},
    {"RETURNSTAT'", "NI", "RETURN'->EXPRESSION"},
    {"RETURNSTAT'", "NPF", "RETURN'->EXPRESSION"},
    {"RETURNSTAT'", "NULL", "RETURN'->EXPRESSION"},
    {"RETURNSTAT'", "OPEN_PARENTHESIS", "RETURN'->EXPRESSION"},
    {"RETURNSTAT'", "PLUS", "RETURN'->EXPRESSION"},
    {"RETURNSTAT'", "SEMICOLON", "RETURN'->EPSILON"},
    {"RETURNSTAT'", "STRC", "RETURN'->EXPRESSION"},
    {"STATELIST", "$", "STATELIST->EPSILON"},
    {"STATELIST", "BREAK", "STATELIST->STMT"},
    {"STATELIST", "FLOAT", "STATELIST->STMT"},
    {"STATELIST", "FOR", "STATELIST->STMT"},
    {"STATELIST", "IDENT", "STATELIST->STMT"},
    {"STATELIST", "IF", "STATELIST->STMT"},
    {"STATELIST", "INT", "STATELIST->STMT"},
    {"STATELIST", "ONECHAR", "STATELIST->STMT"},
    {"STATELIST", "PRINT", "STATELIST->STMT"},
    {"STATELIST", "READ", "STATELIST->STMT"},
    {"STATELIST", "RETURN", "STATELIST->STMT"},
    {"STATELIST", "SEMICOLON", "STATELIST->STMT"},
    {"STATELIST", "STRING", "STATELIST->STMT"},
    {"STATELIST'", "$", "STATELIST'->EPSILON"},
    {"STATELIST'", "BREAK", "STATELIST'->STMT"},
    {"STATELIST'", "CLOSE_BRACE", "STATELIST'->EPSILON"},
    {"STATELIST'", "FLOAT", "STATELIST'->STMT"},
    {"STATELIST'", "FOR", "STATELIST'->STMT"},
    {"STATELIST'", "IDENT", "STATELIST'->STMT"},
    {"STATELIST'", "IF", "STATELIST'->STMT"},
    {"STATELIST'", "INT", "STATELIST'->STMT"},
    {"STATELIST'", "ONECHAR", "STATELIST'->STMT"},
    {"STATELIST'", "PRINT", "STATELIST'->STMT"},
    {"STATELIST'", "READ", "STATELIST'->STMT"},
    {"STATELIST'", "RETURN", "STATELIST'->STMT"},
    {"STATELIST'", "SEMICOLON", "STATELIST'->STMT"},
    {"STATELIST'", "STRING", "STATELIST'->STMT"},
    {"STATEMENT", "BREAK", "STMT->BREAK"},
    {"STATEMENT", "FLOAT", "STMT->VARDECL"},
    {"STATEMENT", "FOR", "STMT->FOR"},
    {"STATEMENT", "IDENT", "STMT->ATRIBSTAT"},
    {"STATEMENT", "IF", "STMT->IF"},
    {"STATEMENT", "INT", "STMT->VARDECL"},
    {"STATEMENT", "ONECHAR", "STMT->BLOCK"},
    {"STATEMENT", "PRINT", "STMT->PRINT"},
    {"STATEMENT", "READ", "STMT->READ"},
    {"STATEMENT", "RETURN", "STMT->RETURN"},
    {"STATEMENT", "SEMICOLON", "STMT->EMPTY"},
    {"STATEMENT", "STRING", "STMT->VARDECL"},
    {"TERM", "IDENT", "TERM->UNARY"},
    {"TERM", "MINUS", "TERM->UNARY"},
    {"TERM", "NI", "TERM->UNARY"},
    {"TERM", "NPF", "TERM->UNARY"},
    {"TERM", "NULL", "TERM->UNARY"},
    {"TERM", "OPEN_PARENTHESIS", "TERM->UNARY"},
    {"TERM", "PLUS", "TERM->UNARY"},
    {"TERM", "STRC", "TERM->UNARY"},
    {"UNARYEXPR", "IDENT", "UNARY->FACTOR"},
    {"UNARYEXPR", "MINUS", "UNARY->PLUS_MINUS"},
    {"UNARYEXPR", "NI", "UNARY->FACTOR"},
    {"UNARYEXPR", "NPF", "UNARY->FACTOR"},
    {"UNARYEXPR", "NULL", "UNARY->FACTOR"},
    {"UNARYEXPR", "OPEN_PARENTHESIS", "UNARY->FACTOR"},
    {"UNARYEXPR", "PLUS", "UNARY->PLUS_MINUS"},
    {"UNARYEXPR", "STRC", "UNARY->FACTOR"},
    {"UNARYEXPRAUX", "CLOSE_BRACKET", "UNARY_AUX->EPSILON"},
    {"UNARYEXPRAUX", "CLOSE_PARENTHESIS", "UNARY_AUX->EPSILON"},
    {"UNARYEXPRAUX", "DIVISION", "UNARY_AUX->DIV"},
    {"UNARYEXPRAUX", "MINUS", "UNARY_AUX->EPSILON"},
    {"UNARYEXPRAUX", "MODULUS", "UNARY_AUX->MOD"},
    {"UNARYEXPRAUX", "MULTIPLICATION", "UNARY_AUX->MULT"},
    {"UNARYEXPRAUX", "PLUS", "UNARY_AUX->EPSILON"},
    {"UNARYEXPRAUX", "RELOP", "UNARY_AUX->EPSILON"},
    {"UNARYEXPRAUX", "SEMICOLON", "UNARY_AUX->EPSILON"},
    {"VARDECL", "FLOAT", "VARDECL->FLOAT"},
    {"VARDECL", "INT", "VARDECL->INT"},
    {"VARDECL", "STRING", "VARDECL->STRING"},
};

const size_t num_entradas_tabela = sizeof(tabela_analise) / sizeof(EntradaTabelaAnalise);

static int comparar_sdt_chave(const void* a, const void* b)
{
    // 'a' é um ponteiro para a CHAVE que estamos procurando (uma string).
    const char* chave_busca = (const char*)a;

    // 'b' é um ponteiro para um ELEMENTO do array.
    const EntradaTabelaSDT* elemento_array = (const EntradaTabelaSDT*)b;

    // Compara a string de busca com o campo 'chave' do elemento do array.
    return strcmp(chave_busca, elemento_array->chave);
}

const EntradaTabelaSDT* buscar_entrada_sdt(const char* chave)
{
    if (!chave) return NULL;

    return (const EntradaTabelaSDT*)bsearch(
        chave,                     // A chave que estamos buscando (já é um ponteiro para char)
        tabela_sdt_entradas,       // O array ordenado
        num_entradas_sdt,          // O número de elementos no array
        sizeof(EntradaTabelaSDT),  // O tamanho de cada elemento do array
        comparar_sdt_chave         // A nova função de comparação
    );
}