#include <stddef.h>

#include "acoes_semanticas.h"
#include "tabela_analise.h"

/*
 * IMPORTANTE — ORDEM LEXICOGRÁFICA OBRIGATÓRIA
 *
 * Esta tabela **precisa** permanecer estritamente ordenada
 * em ordem lexicográfica. Qualquer entrada fora de ordem
 * faz com que as buscas binárias (bsearch) falhem e o
 * compilador passe a produzir resultados incorretos.
 *
 * ➜ Ao adicionar ou remover regras:
 *     1. Insira‑as já na posição correta.
 *     2. Verifique a ordem com um script ou diff.
 *
 * Não ignore este aviso: desordenar a lista quebra o
 * compilador.
 */

const EntradaTabelaSDT tabela_sdt_entradas[] = {
    {"ALLOCAUX->BRACKET",
     {{SIMBOLO, .simbolo = "OPEN_BRACKET"},
      {SIMBOLO, .simbolo = "NUMEXPRESSION"},
      {SIMBOLO, .simbolo = "CLOSE_BRACKET"},
      {SIMBOLO, .simbolo = "ALLOCAUX"},
      {ACAO, .acao = AEXP_coletar_indice}},
     5},
    {"ALLOCAUX->EPSILON",
     {{ACAO, .acao = AEXP_inicializar_contador_vetor}, {SIMBOLO, .simbolo = "ε"}},
     2},
    {"ALLOCEXPR'->TYPE",
     {{SIMBOLO, .simbolo = "VARDECL"},
      {SIMBOLO, .simbolo = "OPEN_BRACKET"},
      {SIMBOLO, .simbolo = "NUMEXPRESSION"},
      {SIMBOLO, .simbolo = "CLOSE_BRACKET"},
      {SIMBOLO, .simbolo = "ALLOCAUX"},
      {ACAO, .acao = AEXP_imprimir_expressao2}},
     6},
    {"ALLOCEXPR->NEW", {{SIMBOLO, .simbolo = "NEW"}, {SIMBOLO, .simbolo = "ALLOCEXPRESSION'"}}, 2},
    {"ATRIB'->ALLOCEXPR", {{SIMBOLO, .simbolo = "ALLOCEXPRESSION"}}, 1},
    {"ATRIB'->EXPRESSION",
     {{SIMBOLO, .simbolo = "EXPRESSION"}, {ACAO, .acao = CODIGO_definir_valor_expressao}},
     2},
    {"ATRIB'->FUNCCALL",
     {{SIMBOLO, .simbolo = "FUNCCALL"}, {ACAO, .acao = CODIGO_lidar_atribuicao_funcao}},
     2},
    {"ATRIBSTAT->IDENT",
     {{ACAO, .acao = CODIGO_herdar_proximo},
      {SIMBOLO, .simbolo = "LVALUE"},
      {SIMBOLO, .simbolo = "ASSIGN"},
      {SIMBOLO, .simbolo = "ATRIBSTAT'"},
      {ACAO, .acao = CODIGO_atribuicao}},
     5},
    {"CLOSE_BRACE->EPSILON", {{ACAO, .acao = ESCOPO_acao2}, {SIMBOLO, .simbolo = "ε"}}, 2},
    {"EXPR'->EPSILON", {{SIMBOLO, .simbolo = "ε"}}, 1},
    {"EXPR'->RELOP",
     {{SIMBOLO, .simbolo = "RELOP"},
      {SIMBOLO, .simbolo = "NUMEXPRESSION"},
      {ACAO, .acao = AEXP_imprimir_expressao1},
      {ACAO, .acao = CODIGO_relop_action}},
     4},
    {"EXPR->NUMEXPR",
     {{SIMBOLO, .simbolo = "NUMEXPRESSION"},
      {ACAO, .acao = AEXP_imprimir_expressao0_h},
      {SIMBOLO, .simbolo = "EXPRESSION'"},
      {ACAO, .acao = AEXP_imprimir_expressao0}},
     4},
    {"FACTOR->CONST_NI", {{SIMBOLO, .simbolo = "NI"}, {ACAO, .acao = AEXP_lexema_para_valor}}, 2},
    {"FACTOR->CONST_NPF", {{SIMBOLO, .simbolo = "NPF"}, {ACAO, .acao = AEXP_lexema_para_valor}}, 2},
    {"FACTOR->CONST_NULL", {{SIMBOLO, .simbolo = "NULL"}}, 1},
    {"FACTOR->CONST_STRC",
     {{SIMBOLO, .simbolo = "STRC"}, {ACAO, .acao = AEXP_lexema_para_valor}},
     2},
    {"FACTOR->LVALUE", {{SIMBOLO, .simbolo = "LVALUE"}, {ACAO, .acao = AEXP_ident_para_cima}}, 2},
    {"FACTOR->PARENTHESIS",
     {{SIMBOLO, .simbolo = "OPEN_PARENTHESIS"},
      {SIMBOLO, .simbolo = "NUMEXPRESSION"},
      {SIMBOLO, .simbolo = "CLOSE_PARENTHESIS"},
      {ACAO, .acao = AEXP_passar_numero}},
     4},
    {"FORSTAT->FOR",
     {{ACAO, .acao = CODIGO_herdar_proximo_for},
      {SIMBOLO, .simbolo = "FOR"},
      {SIMBOLO, .simbolo = "OPEN_PARENTHESIS"},
      {SIMBOLO, .simbolo = "ATRIBSTAT"},
      {SIMBOLO, .simbolo = "SEMICOLON"},
      {SIMBOLO, .simbolo = "EXPRESSION"},
      {SIMBOLO, .simbolo = "SEMICOLON"},
      {SIMBOLO, .simbolo = "ATRIBSTAT"},
      {SIMBOLO, .simbolo = "CLOSE_PARENTHESIS"},
      {ACAO, .acao = CODIGO_for_setup_h},
      {ACAO, .acao = ESCOPO_acao7},
      {SIMBOLO, .simbolo = "STATELIST"},
      {ACAO, .acao = ESCOPO_acao2},
      {ACAO, .acao = CODIGO_acao_for_s}},
     14},
    {"FUNCCALL->CALL",
     {{SIMBOLO, .simbolo = "CALL"},
      {SIMBOLO, .simbolo = "OPEN_PARENTHESIS"},
      {SIMBOLO, .simbolo = "IDENT"},
      {ACAO, .acao = DECLARAR_VERIFICAR_acao1},
      {SIMBOLO, .simbolo = "OPEN_PARENTHESIS"},
      {SIMBOLO, .simbolo = "PARAMLISTCALL"},
      {SIMBOLO, .simbolo = "CLOSE_PARENTHESIS"},
      {SIMBOLO, .simbolo = "CLOSE_PARENTHESIS"},
      {ACAO, .acao = CODIGO_chamada_funcao}},
     9},
    {"FUNCDEF->DEF",
     {{SIMBOLO, .simbolo = "DEF"},
      {SIMBOLO, .simbolo = "IDENT"},
      {ACAO, .acao = CODIGO_funcdef_h},
      {ACAO, .acao = ESCOPO_acao3},
      {ACAO, .acao = DEC_acao1},
      {ACAO, .acao = ESCOPO_acao4},
      {SIMBOLO, .simbolo = "OPEN_PARENTHESIS"},
      {SIMBOLO, .simbolo = "PARAMLIST"},
      {SIMBOLO, .simbolo = "CLOSE_PARENTHESIS"},
      {SIMBOLO, .simbolo = "ONECHAR"},
      {SIMBOLO, .simbolo = "STATELIST"},
      {SIMBOLO, .simbolo = "CLOSE_BRACE"},
      {ACAO, .acao = ESCOPO_acao2},
      {ACAO, .acao = CODIGO_funcdef_s}},
     14},
    {"FUNCLIST'->DEF",
     {{ACAO, .acao = CODIGO_herdar_proximo},
      {SIMBOLO, .simbolo = "FUNCLIST"},
      {ACAO, .acao = CODIGO_obter_codigo_filhos}},
     3},
    {"FUNCLIST'->EPSILON", {{SIMBOLO, .simbolo = "ε"}}, 1},
    {"FUNCLIST->DEF",
     {{ACAO, .acao = CODIGO_herdar_proximo},
      {SIMBOLO, .simbolo = "FUNCDEF"},
      {SIMBOLO, .simbolo = "FUNCLIST'"},
      {ACAO, .acao = CODIGO_obter_codigo_filhos}},
     4},
    {"IFSTAT'->ELSE",
     {{ACAO, .acao = CODIGO_acao_else_h},
      {SIMBOLO, .simbolo = "ELSE"},
      {SIMBOLO, .simbolo = "ONECHAR"},
      {ACAO, .acao = ESCOPO_acao6},
      {SIMBOLO, .simbolo = "STATEMENT"},
      {SIMBOLO, .simbolo = "CLOSE_BRACE"},
      {ACAO, .acao = ESCOPO_acao2},
      {ACAO, .acao = CODIGO_acao_else_s}},
     8},
    {"IFSTAT'->EPSILON", {{ACAO, .acao = CODIGO_acao_else_vazio}, {SIMBOLO, .simbolo = "ε"}}, 2},
    {"IFSTAT->IF",
     {{ACAO, .acao = CODIGO_herdar_proximo},
      {SIMBOLO, .simbolo = "IF"},
      {SIMBOLO, .simbolo = "OPEN_PARENTHESIS"},
      {SIMBOLO, .simbolo = "EXPRESSION"},
      {SIMBOLO, .simbolo = "CLOSE_PARENTHESIS"},
      {SIMBOLO, .simbolo = "ONECHAR"},
      {ACAO, .acao = ESCOPO_acao5},
      {SIMBOLO, .simbolo = "STATELIST"},
      {SIMBOLO, .simbolo = "CLOSE_BRACE"},
      {ACAO, .acao = ESCOPO_acao2},
      {SIMBOLO, .simbolo = "IFSTAT'"},
      {ACAO, .acao = CODIGO_acao_if_s}},
     12},
    {"INDEX->BRACKET",
     {{SIMBOLO, .simbolo = "OPEN_BRACKET"},
      {SIMBOLO, .simbolo = "NI"},
      {SIMBOLO, .simbolo = "CLOSE_BRACKET"},
      {ACAO, .acao = DEC_acao5},
      {SIMBOLO, .simbolo = "INDEX"},
      {ACAO, .acao = DEC_acao6}},
     6},
    {"INDEX->EPSILON", {{SIMBOLO, .simbolo = "ε"}, {ACAO, .acao = DEC_acao7}}, 2},
    {"LVALUE->IDENT",
     {{SIMBOLO, .simbolo = "IDENT"},
      {SIMBOLO, .simbolo = "ALLOCAUX"},
      {ACAO, .acao = AEXP_avaliar_identificador_lvalue}},
     3},
    {"NUMEXPR->TERM",
     {{SIMBOLO, .simbolo = "TERM"},
      {SIMBOLO, .simbolo = "NUMEXPRESSIONAUX"},
      {ACAO, .acao = AEXP_gerar_no}},
     3},
    {"NUMEXPR_AUX->EPSILON", {{SIMBOLO, .simbolo = "ε"}}, 1},
    {"NUMEXPR_AUX->MINUS",
     {{SIMBOLO, .simbolo = "MINUS"},
      {SIMBOLO, .simbolo = "TERM"},
      {SIMBOLO, .simbolo = "NUMEXPRESSIONAUX"}},
     3},
    {"NUMEXPR_AUX->PLUS",
     {{SIMBOLO, .simbolo = "PLUS"},
      {SIMBOLO, .simbolo = "TERM"},
      {SIMBOLO, .simbolo = "NUMEXPRESSIONAUX"}},
     3},
    {"PARAMLIST'->COMMA", {{SIMBOLO, .simbolo = "COMMA"}, {SIMBOLO, .simbolo = "PARAMLIST"}}, 2},
    {"PARAMLIST'->EPSILON", {{SIMBOLO, .simbolo = "ε"}}, 1},
    {"PARAMLIST->EPSILON", {{SIMBOLO, .simbolo = "ε"}}, 1},
    {"PARAMLIST->TYPE", {{SIMBOLO, .simbolo = "VARDECL"}, {SIMBOLO, .simbolo = "PARAMLIST'"}}, 2},
    {"PARAMLISTCALL'->COMMA",
     {{SIMBOLO, .simbolo = "COMMA"},
      {SIMBOLO, .simbolo = "PARAMLISTCALL"},
      {ACAO, .acao = CODIGO_obter_parametros}},
     3},
    {"PARAMLISTCALL'->EPSILON", {{SIMBOLO, .simbolo = "ε"}}, 1},
    {"PARAMLISTCALL->EPSILON", {{SIMBOLO, .simbolo = "ε"}}, 1},
    {"PARAMLISTCALL->LVALUE",
     {{SIMBOLO, .simbolo = "LVALUE"},
      {ACAO, .acao = DECLARAR_VERIFICAR_acao2},
      {SIMBOLO, .simbolo = "PARAMLISTCALL'"},
      {ACAO, .acao = CODIGO_chamada_paramlist}},
     4},
    {"PRINTSTAT->PRINT",
     {{SIMBOLO, .simbolo = "PRINT"},
      {SIMBOLO, .simbolo = "EXPRESSION"},
      {ACAO, .acao = CODIGO_lidar_impressao}},
     3},
    {"PROG'->EPSILON", {{SIMBOLO, .simbolo = "ε"}}, 1},
    {"PROG'->FUNCLIST",
     {{ACAO, .acao = CODIGO_herdar_proximo},
      {SIMBOLO, .simbolo = "FUNCLIST"},
      {ACAO, .acao = CODIGO_obter_codigo_filhos}},
     3},
    {"PROG'->STATEMENT",
     {{ACAO, .acao = CODIGO_herdar_proximo},
      {SIMBOLO, .simbolo = "STATEMENT"},
      {ACAO, .acao = CODIGO_obter_codigo_filhos}},
     3},
    {"PROG->EPSILON", {{ACAO, .acao = ESCOPO_acao1}, {SIMBOLO, .simbolo = "ε"}}, 2},
    {"PROG->FUNCLIST",
     {{ACAO, .acao = ESCOPO_acao1},
      {ACAO, .acao = CODIGO_definir_rotulo_final},
      {ACAO, .acao = CODIGO_herdar_proximo},
      {SIMBOLO, .simbolo = "FUNCLIST"},
      {SIMBOLO, .simbolo = "PROGRAM'"},
      {ACAO, .acao = CODIGO_ir_para_principal},
      {ACAO, .acao = CODIGO_gerar_codigo_final}},
     7},
    {"PROG->STATEMENT",
     {{ACAO, .acao = ESCOPO_acao1},
      {ACAO, .acao = CODIGO_definir_rotulo_final},
      {ACAO, .acao = CODIGO_herdar_proximo},
      {SIMBOLO, .simbolo = "STATEMENT"},
      {ACAO, .acao = CODIGO_obter_codigo_filhos},
      {ACAO, .acao = CODIGO_gerar_codigo_final}},
     6},
    {"READSTAT->READ",
     {{SIMBOLO, .simbolo = "READ"},
      {SIMBOLO, .simbolo = "LVALUE"},
      {ACAO, .acao = CODIGO_lidar_leitura}},
     3},

    {"RETURN'->EPSILON", {{SIMBOLO, .simbolo = "ε"}}, 1},
    {"RETURN'->EXPRESSION",
     {{SIMBOLO, .simbolo = "EXPRESSION"}, {ACAO, .acao = CODIGO_lidar_retorno2}},
     2},
    {"RETURNSTAT->RETURN",
     {{SIMBOLO, .simbolo = "RETURN"},
      {SIMBOLO, .simbolo = "RETURNSTAT'"},
      {ACAO, .acao = CODIGO_lidar_retorno}},
     3},
    {"STATELIST'->EPSILON", {{SIMBOLO, .simbolo = "ε"}}, 1},
    {"STATELIST'->STMT",
     {{ACAO, .acao = CODIGO_herdar_proximo},
      {ACAO, .acao = CODIGO_definir_proximo_filho},
      {SIMBOLO, .simbolo = "STATEMENT"},
      {SIMBOLO, .simbolo = "STATELIST'"},
      {ACAO, .acao = CODIGO_combinar_codigo_para_lista}},
     5},
    {"STATELIST->EPSILON", {{ACAO, .acao = ESCOPO_acao2}, {SIMBOLO, .simbolo = "ε"}}, 2},
    {"STATELIST->STMT",
     {{ACAO, .acao = CODIGO_herdar_proximo},
      {ACAO, .acao = CODIGO_definir_proximo_filho},
      {SIMBOLO, .simbolo = "STATEMENT"},
      {SIMBOLO, .simbolo = "STATELIST'"},
      {ACAO, .acao = CODIGO_combinar_codigo_para_lista}},
     5},
    {"STMT->ATRIBSTAT",
     {{ACAO, .acao = CODIGO_herdar_proximo},
      {SIMBOLO, .simbolo = "ATRIBSTAT"},
      {SIMBOLO, .simbolo = "SEMICOLON"},
      {ACAO, .acao = CODIGO_obter_codigo_filhos}},
     4},
    {"STMT->BLOCK",
     {{ACAO, .acao = CODIGO_herdar_proximo},
      {SIMBOLO, .simbolo = "ONECHAR"},
      {ACAO, .acao = ESCOPO_acao1},
      {SIMBOLO, .simbolo = "STATELIST"},
      {SIMBOLO, .simbolo = "CLOSE_BRACE"},
      {ACAO, .acao = ESCOPO_acao2},
      {ACAO, .acao = CODIGO_obter_codigo_filhos}},
     7},
    {"STMT->BREAK",
     {{SIMBOLO, .simbolo = "BREAK"},
      {ACAO, .acao = BREAK_acao1},
      {SIMBOLO, .simbolo = "SEMICOLON"},
      {ACAO, .acao = CODIGO_lidar_break}},
     4},
    {"STMT->EMPTY", {{SIMBOLO, .simbolo = "SEMICOLON"}}, 1},
    {"STMT->FOR",
     {{ACAO, .acao = CODIGO_herdar_proximo},
      {SIMBOLO, .simbolo = "FORSTAT"},
      {ACAO, .acao = CODIGO_obter_codigo_filhos}},
     3},
    {"STMT->IF",
     {{ACAO, .acao = CODIGO_herdar_proximo},
      {SIMBOLO, .simbolo = "IFSTAT"},
      {ACAO, .acao = CODIGO_obter_codigo_filhos}},
     3},
    {"STMT->PRINT",
     {{ACAO, .acao = CODIGO_herdar_proximo},
      {SIMBOLO, .simbolo = "PRINTSTAT"},
      {SIMBOLO, .simbolo = "SEMICOLON"},
      {ACAO, .acao = CODIGO_obter_codigo_filhos}},
     4},
    {"STMT->READ",
     {{ACAO, .acao = CODIGO_herdar_proximo},
      {SIMBOLO, .simbolo = "READSTAT"},
      {SIMBOLO, .simbolo = "SEMICOLON"},
      {ACAO, .acao = CODIGO_obter_codigo_filhos}},
     4},
    {"STMT->RETURN",
     {{ACAO, .acao = CODIGO_herdar_proximo},
      {SIMBOLO, .simbolo = "RETURNSTAT"},
      {SIMBOLO, .simbolo = "SEMICOLON"},
      {ACAO, .acao = CODIGO_obter_codigo_filhos}},
     4},
    {"STMT->VARDECL",
     {{SIMBOLO, .simbolo = "VARDECL"},
      {SIMBOLO, .simbolo = "SEMICOLON"},
      {ACAO, .acao = CODIGO_obter_codigo_filhos}},
     3},
    {"TERM->UNARY",
     {{SIMBOLO, .simbolo = "UNARYEXPR"},
      {SIMBOLO, .simbolo = "UNARYEXPRAUX"},
      {ACAO, .acao = AEXP_termo}},
     3},
    {"UNARY->FACTOR", {{SIMBOLO, .simbolo = "FACTOR"}, {ACAO, .acao = AEXP_valor_para_cima}}, 2},
    {"UNARY->PLUS_MINUS",
     {{SIMBOLO, .simbolo = "PLUS_MINUS"},
      {SIMBOLO, .simbolo = "FACTOR"},
      {ACAO, .acao = AEXP_valor_segundo_filho_para_cima}},
     3},
    {"UNARY_AUX->DIV",
     {{SIMBOLO, .simbolo = "DIVISION"},
      {SIMBOLO, .simbolo = "UNARYEXPR"},
      {SIMBOLO, .simbolo = "UNARYEXPRAUX"}},
     3},
    {"UNARY_AUX->EPSILON", {{SIMBOLO, .simbolo = "ε"}}, 1},
    {"UNARY_AUX->MOD",
     {{SIMBOLO, .simbolo = "MODULUS"},
      {SIMBOLO, .simbolo = "UNARYEXPR"},
      {SIMBOLO, .simbolo = "UNARYEXPRAUX"}},
     3},
    {"UNARY_AUX->MULT",
     {{SIMBOLO, .simbolo = "MULTIPLICATION"},
      {SIMBOLO, .simbolo = "UNARYEXPR"},
      {SIMBOLO, .simbolo = "UNARYEXPRAUX"}},
     3},
    {"VARDECL->FLOAT",
     {{SIMBOLO, .simbolo = "FLOAT"},
      {SIMBOLO, .simbolo = "IDENT"},
      {ACAO, .acao = ESCOPO_acao3},
      {ACAO, .acao = DEC_acao9},
      {SIMBOLO, .simbolo = "INDEX"},
      {ACAO, .acao = DEC_acao11}},
     6},
    {"VARDECL->INT",
     {{SIMBOLO, .simbolo = "INT"},
      {SIMBOLO, .simbolo = "IDENT"},
      {ACAO, .acao = ESCOPO_acao3},
      {ACAO, .acao = DEC_acao8},
      {SIMBOLO, .simbolo = "INDEX"},
      {ACAO, .acao = DEC_acao11}},
     6},
    {"VARDECL->STRING",
     {{SIMBOLO, .simbolo = "STRING"},
      {SIMBOLO, .simbolo = "IDENT"},
      {ACAO, .acao = ESCOPO_acao3},
      {ACAO, .acao = DEC_acao10},
      {SIMBOLO, .simbolo = "INDEX"},
      {ACAO, .acao = DEC_acao11}},
     6}};

const size_t num_entradas_sdt = sizeof(tabela_sdt_entradas) / sizeof(EntradaTabelaSDT);